In [27]:
import pandas as pd

In [28]:
raw = pd.read_csv('/home/chenjie/Desktop/Math564Project/final_table.csv')

In [29]:
raw.head()

,Season,TEAM,win,loss,pct,home,away,div,conf,ppg,...,TS,AST,TO,USG,ORR,DRR,REBR,PER,VA,EWA
0,2014,SA,62,20,0.756,32-9,30-11,12-4,38-14,105.4,...,0.535,15.4,11.2,23.5,8.6,28.3,18.8,21.40,318.8,10.6
1,2014,SA,62,20,0.756,32-9,30-11,12-4,38-14,105.4,...,0.590,25.7,12.2,24.2,2.3,12.0,7.3,20.06,221.2,7.4
2,2014,SA,62,20,0.756,32-9,30-11,12-4,38-14,105.4,...,0.602,14.6,8.8,17.0,4.6,18.9,12.1,19.43,256.3,8.5
3,2014,SA,62,20,0.756,32-9,30-11,12-4,38-14,105.4,...,0.555,24.9,9.7,25.9,1.0,7.5,4.4,19.00,238.5,7.9
4,2014,SA,62,20,0.756,32-9,30-11,12-4,38-14,105.4,...,0.588,16.3,6.9,21.2,2.6,9.6,6.2,18.80,177.7,5.9

In [30]:
list(raw)

['Season',
 'TEAM',
 'win',
 'loss',
 'pct',
 'home',
 'away',
 'div',
 'conf',
 'ppg',
 'opp_ppg',
 'diff',
 'RK',
 'PLAYER',
 'GP',
 'MPG',
 'TS',
 'AST',
 'TO',
 'USG',
 'ORR',
 'DRR',
 'REBR',
 'PER',
 'VA',
 'EWA']

In [31]:
raw['MPG_Times_PER'] = raw['MPG']*raw['PER']

In [36]:
list(raw)

['Season',
 'TEAM',
 'win',
 'loss',
 'pct',
 'home',
 'away',
 'div',
 'conf',
 'ppg',
 'opp_ppg',
 'diff',
 'RK',
 'PLAYER',
 'GP',
 'MPG',
 'TS',
 'AST',
 'TO',
 'USG',
 'ORR',
 'DRR',
 'REBR',
 'PER',
 'VA',
 'EWA',
 'MPG_Times_PER']

In [35]:
raw.to_csv('table.csv')

In [33]:
raw.groupby(['Season','TEAM'])['MPG'].nlargest(8)

Season  TEAM
2014    ATL   200     33.9
              194     33.5
              193     33.0
              195     32.2
              199     32.1
              197     24.1
              201     20.4
              198     19.4
        BKN   170     32.6
              168     32.2
              165     31.4
              169     28.0
              171     26.0
              175     24.2
              177     22.7
              167     22.2
        BOS   308     34.2
              303     33.3
              309     30.9
              302     27.6
              305     27.6
              307     25.0
              312     24.4
              310     23.4
        CHI   137     38.7
              131     35.3
              135     35.1
              138     31.5
              140     29.0
              133     28.7
                      ...
2018    SAC   1862    27.8
              1860    27.0
              1856    25.6
              1857    25.3
              1864    24.8
              1865    22.1
        TOR   1572    33.9
              1573    32.2
              1577    27.5
              1571    22.4
              1575    20.8
              1578    20.7
              1576    20.0
              1580    20.0
        UTAH  1666    33.4
              1664    32.4
              1670    31.5
              1668    29.3
              1665    28.0
              1671    26.9
              1675    26.1
              1676    21.9
        WSH   1762    36.3
              1761    34.4
              1763    31.6
              1770    27.5
              1767    27.0
              1765    25.3
              1764    22.5
              1766    18.5
Name: MPG, Length: 1192, dtype: float64

In [34]:
raw_sorted

Season  TEAM
2014    ATL   200     33.9
              194     33.5
              193     33.0
              195     32.2
              199     32.1
              197     24.1
              201     20.4
              198     19.4
        BKN   170     32.6
              168     32.2
              165     31.4
              169     28.0
              171     26.0
              175     24.2
              177     22.7
              167     22.2
        BOS   308     34.2
              303     33.3
              309     30.9
              302     27.6
              305     27.6
              307     25.0
              312     24.4
              310     23.4
        CHI   137     38.7
              131     35.3
              135     35.1
              138     31.5
              140     29.0
              133     28.7
                      ...
2018    SAC   1862    27.8
              1860    27.0
              1856    25.6
              1857    25.3
              1864    24.8
              1865    22.1
        TOR   1572    33.9
              1573    32.2
              1577    27.5
              1571    22.4
              1575    20.8
              1578    20.7
              1576    20.0
              1580    20.0
        UTAH  1666    33.4
              1664    32.4
              1670    31.5
              1668    29.3
              1665    28.0
              1671    26.9
              1675    26.1
              1676    21.9
        WSH   1762    36.3
              1761    34.4
              1763    31.6
              1770    27.5
              1767    27.0
              1765    25.3
              1764    22.5
              1766    18.5
Name: MPG, Length: 1192, dtype: float64